### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by ZeteCx** [Soreepeong/XivAlexander#489]
[XivAlexander_20220811_091048_877.log](https://github.com/Soreepeong/XivAlexander/files/9306423/XivAlexander_20220811_091048_877.log)

tried to reinstall and everything, this happen multiple times a day randomally

**Comment by ZeteCx** [comment]
Hey, anyone ran into that problem before? it keep happening

**Comment by strich** [comment]
Same here:
```
Unhandled native exception occurred at cimgui.dll+2E97D	(igTreeNodeBehavior+0x2A750)
Code: C0000005
Dump at: C:\Users\scott\AppData\Roaming\XIVLauncher\addon\Hooks\6.4.0.43\..\..\..\dalamud_appcrash_20220820_152643_673_31880.dmp
Time: 2022-08-20 15:26:44.1415538 GMT+10

   at System.Environment.get_StackTrace()
   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70
   at ImGuiNET.ImGuiNative.igNewFrame()
   at ImGuiNET.ImGuiNative.igNewFrame()
   at ImGuiScene.RawDX11Scene.Render() in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 140
   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr swapChain, UInt32 syncInterval, UInt32 presentFlags) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 535
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 412

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF93D38E97D
Parameters: 0, FFFFFFFFFFFFFFFF
Call Stack
{
  [0]	cimgui.dll+2E97D	(igTreeNodeBehavior+0x2A750)
  [1]	cimgui.dll+2E97D	(igTreeNodeBehavior+0x2A750)
  [2]	cimgui.dll+3AA08	(igTreeNodeBehavior+0x367DB)
  [3]	7FF8E7DAE6EA
  [4]	1F2B47DFED0
  [5]	1F2B47DBD08
  [6]	1
  [7]	5CB12FF130
}
```
