### ISSUE TITLE
Breaks networking in Dalamud

### ISSUE THREAD

**Issue by ascclemens** [Soreepeong/XivAlexander#9]
Hi! Glad to see you've unprivated.

When XivAlexander is enabled and Dalamud is also injected (Dalamud injected first, then XivAlexander opened), networking breaks in Dalamud. For example, adding a custom plugin repository and then opening the plugins window results in the requests all erroring.

```
[18:18:09.835][Information] [PLUGINR] Fetching repo: "https://goatcorp.github.io/DalamudPlugins/pluginmaster.json"
[18:18:09.906][Error] Could not download PluginMaster
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at Dalamud.Plugin.PluginRepository.<ReloadPluginMasterAsync>b__11_0()
```

I have a plugin that establishes a persistent WebSocket connection, as well, and that will eventually break, too.

**Comment by Soreepeong** [comment]
Can you try out with the latest version again? Latest version got IP filtering enabled.

**Comment by ascclemens** [comment]
Oh, I didn't realise you released a new version. My bad. It seems to work in the new one!
